### ISSUE TITLE
fix buy order initiated

### ISSUE THREAD

**Issue by qjflores** [qjflores/exchangemvpreact#147] opened 2017-04-27 14:29 UTC
![fix-buyorder-initiated](https://cloud.githubusercontent.com/assets/5955676/25488155/e4c71ed8-2b98-11e7-914a-e958dce064ae.png)

this happens when a user creates a buy order, goes to their dashboard and clicks on edit from the your trade advertisement component

**Comment by adklempner** [comment] 2017-04-28 10:49
duplicate of #153

**Closed by adklempner** 2017-04-28 10:49 UTC
